### ISSUE TITLE
Amazon Bedrock Agent Samples - [Bug]

### ISSUE THREAD

**Issue by kkeli** [awslabs/amazon-bedrock-agent-samples#3]
**Describe the bug**
A clear and concise description of what the bug is. This could be anything from:

1. A typo or text changes that make the lab better.... to
2. minor annoying code that still works.. to
3. breaking changes

**To Reproduce**
Steps to reproduce the behavior (or some version of this):
1. Go to 'examples/amazon-bedrock-multi-agent-collaboration/energy_efficiency_management_agent'
2. Execute "pip install -r src/requirements.txt" will failed as the correct command is "**pip install -r requirements.txt**" without "**src/**"

**Expected behavior**
Install all libs

**Comment by EashanKaushik** [comment]
Thanks for pointing out the inconsistencies with docs.
